/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_crimsonwoods_android_libs_uvccap_ColorConverter */

#ifndef _Included_net_crimsonwoods_android_libs_uvccap_ColorConverter
#define _Included_net_crimsonwoods_android_libs_uvccap_ColorConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_crimsonwoods_android_libs_uvccap_ColorConverter
 * Method:    yuyvtorgb
 * Signature: ([I[BII)V
 */
JNIEXPORT void JNICALL Java_net_crimsonwoods_android_libs_uvccap_ColorConverter_yuyvtorgb
  (JNIEnv *, jclass, jintArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
