/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_ubilabo_android_apps_uvccapture_ColorConverter */

#ifndef _Included_net_ubilabo_android_apps_uvccapture_ColorConverter
#define _Included_net_ubilabo_android_apps_uvccapture_ColorConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_ubilabo_android_apps_uvccapture_ColorConverter
 * Method:    yuyvtorgb
 * Signature: ([I[BII)V
 */
JNIEXPORT void JNICALL Java_net_ubilabo_android_apps_uvccapture_ColorConverter_yuyvtorgb
  (JNIEnv *, jclass, jintArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
